name = "WalesTaxation"
uuid = "61172c1e-963a-4210-8d85-db860d54c0c2"
authors = ["Graham Stark"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
